### ISSUE TITLE
Accurev workspace root is tied to VSCode workspace root

### ISSUE THREAD

**Issue by markacx** [bluemonkmn/vscode-accurev#1]
Firstly, I am thrilled someone is working on an extension for AccuRev.  I actually wrote one for Netbeans way back in the day, which mostly only did file status and diffs.  (The write operations, with the exception a keep for a rename operation, I just did in the main AccuRev UI.)

Having the in-editor feedback of which lines were changed was the most important thing to me.

Anyway, I am unable to use this right now because, I believe, the plugin is assuming that the Workspace root is the same as the root of the VSCode application.  We have several projects in our repository, so the AccuRev workspace root is above VSCode's workspace root.

I am not sure how much time I have to give to this right now, but if you want a team-member for this project, I am willing to do what I can.  Thanks!

**Comment by bluemonkmn** [comment]
Yes, you're not the first to report that, so that was the first problem I figured I (or someone) should address. I hope to get your help soon, but I can't discuss just yet.

**Comment by bluemonkmn** [comment]
Sorry for the delay. Bureaucracies are slowing down the sharing of my work, but I have fixed the problem (and I think it's even checked in and pushed to the shared repository) but circumstances are slowing down my formal release of the fix.

**Comment by bluemonkmn** [comment]
The version with the fix has just been published (0.0.2), as has the subsequent version with some other enhancements (0.0.3).
